# Generated by Django 2.2.6 on 2019-11-06 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoremanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_specification',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_has_score',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_has_score', to='scoremanager.Score', verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='user_has_score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_has_scores', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
