# Generated by Django 2.2.6 on 2019-11-06 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoremanager', '0003_auto_20191105_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_has_score',
            name='score_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
