# Generated by Django 2.2.6 on 2019-11-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoremanager', '0004_user_has_score_score_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_has_score',
            name='admin_username',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
