# Generated by Django 2.2.6 on 2019-11-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
