# Generated by Django 2.2.5 on 2019-10-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191017_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
