# Generated by Django 2.2.5 on 2019-10-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191018_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='name',
        ),
    ]
