# Generated by Django 2.2.5 on 2019-10-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191018_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
