# Generated by Django 2.2.5 on 2019-10-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191018_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='scores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pontuacao'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='sexUser',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
