# Generated by Django 2.2.5 on 2019-10-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191018_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='scores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pontuacao'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='sexUser',
            field=models.CharField(max_length=100, verbose_name='Sex'),
        ),
    ]
