# Generated by Django 2.2.5 on 2019-10-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191018_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pontuacoes',
        ),
    ]
