# Generated by Django 2.2.5 on 2019-10-19 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20191019_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_description', models.TextField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Score',
            },
        ),
        migrations.CreateModel(
            name='User_has_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_comment', models.TextField(max_length=255, verbose_name='Comment')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Score')),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='idUsuario',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.RemoveField(
            model_name='usuario_possui_pontuacao',
            name='nomeUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario_possui_pontuacao',
            name='pontuacaoUsuario',
        ),
        migrations.RenameField(
            model_name='ranking',
            old_name='pontuacaoTotal',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='ranking',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Pontuacao',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Usuario_possui_pontuacao',
        ),
    ]
