# Generated by Django 2.2.5 on 2019-10-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191019_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Pontuação'},
        ),
        migrations.AlterField(
            model_name='score',
            name='score_description',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='user_has_score',
            name='score_comment',
            field=models.TextField(max_length=255, verbose_name='Comentário'),
        ),
    ]
