# Generated by Django 2.2.5 on 2019-10-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191019_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Pontuação', 'verbose_name_plural': 'Pontuações'},
        ),
    ]
