# Generated by Django 2.2.5 on 2019-10-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191019_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_has_score',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_has_score',
            name='user_score',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='User_has_score',
        ),
    ]
