# Generated by Django 2.2.5 on 2019-11-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191024_0028'),
        ('users', '0004_auto_20191026_1259'),
    ]

    operations = [
    ]
